version: '3'
services:
  skyler-ui:
    build:
      context: .
    restart: always
    container_name: skyler-ui
    image: skyler-ui
    networks:
      - spring_cloud_default
    external_links:
      - skyler-gateway
    ports:
      - 80:80

# 加入到后端网络， 默认为 spring_cloud_default  | docker network ls   查看
networks:
  spring_cloud_default:
    external: true
